## conda env update --file environment.yml --prune
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - autopep8
  - pip:
    - hydra-core
    - lightning
    - rootutils
